/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.libroteca.views;

import java.awt.Color;
import java.io.BufferedReader;
import java.io.ByteArrayInputStream;
import java.io.IOException;
import java.io.InputStreamReader;
import javax.swing.JOptionPane;

/**
 *
 * @author Torturado UTP
 */
public class Inicio extends javax.swing.JPanel {

    private String Nombre;
    private String edad;
    private String carrera;
    private String hobbies;

    /**
     * Creates new form Inicio
     */
    public Inicio() {
        initComponents();
        initStyles();
        
    }
    
    
    public void initStyles(){
    bienvenido_text.putClientProperty( "FlatLaf.style", "font: bold $h1.regular.font" );
    bienvenido_text.setForeground(Color.black);
    descripcion_text.putClientProperty( "FlatLaf.style", "font: $large.font" );
    descripcion_text.setForeground(Color.black);
    
    utepe_text.putClientProperty( "FlatLaf.style", "font: $large.font" );
    utepe_text.setForeground(Color.black);
    
    funcionalidades_text.setForeground(Color.black);
    func1_text.setForeground(Color.black);
    func2_text.setForeground(Color.black);
    func3_text.setForeground(Color.black);
    preguntas_text.setForeground(Color.black);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fondo = new javax.swing.JPanel();
        bienvenido_text = new javax.swing.JLabel();
        descripcion_text = new javax.swing.JLabel();
        funcionalidades_text = new javax.swing.JLabel();
        func1_text = new javax.swing.JLabel();
        func3_text = new javax.swing.JLabel();
        func2_text = new javax.swing.JLabel();
        preguntas_text = new javax.swing.JLabel();
        claro_pregunteme_button = new javax.swing.JButton();
        personaleyendo = new javax.swing.JLabel();
        utepe_text = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        fondo.setBackground(new java.awt.Color(255, 255, 255));

        bienvenido_text.setText("¡Bienvenido! Espero que disfrutes de tu lectura");

        descripcion_text.setText("Aplicacion de Libreria Digital para la comoda y facil lectura!");

        funcionalidades_text.setText("Funcionalidades:");

        func1_text.setText("• Ver Estadisticas de Lectura (Libros sugeridos segun tus gustos)");

        func3_text.setText("• Ver Catalogo");

        func2_text.setText("• Ver Libros Preferidos (Libreria personal)");

        preguntas_text.setText("Antes de comenzar necesitamos hacerte un par de preguntas:");

        claro_pregunteme_button.setBackground(new java.awt.Color(153, 0, 255));
        claro_pregunteme_button.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        claro_pregunteme_button.setForeground(new java.awt.Color(255, 255, 255));
        claro_pregunteme_button.setText("¡Claro Preguntame!");
        claro_pregunteme_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                claro_pregunteme_buttonActionPerformed(evt);
            }
        });

        personaleyendo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        personaleyendo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resourcess/personaleyendo.png"))); // NOI18N

        utepe_text.setText("Universidad Tecnologica de Panama");

        jLabel1.setText("Jose Rodriguez 8-1024-1828");

        jLabel2.setText("Anibal Abrego 8-1029-1015");

        jLabel3.setText("Luis Tapia 8-1015-2280");

        jLabel4.setText("Jim Santos 8-1019-135");

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resourcess/urtepe.jpg"))); // NOI18N

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resourcess/fiscLogo.png"))); // NOI18N

        javax.swing.GroupLayout fondoLayout = new javax.swing.GroupLayout(fondo);
        fondo.setLayout(fondoLayout);
        fondoLayout.setHorizontalGroup(
            fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fondoLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(bienvenido_text, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(fondoLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(descripcion_text, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jLabel5)
                .addGap(20, 20, 20)
                .addComponent(utepe_text)
                .addGap(10, 10, 10)
                .addComponent(jLabel6))
            .addGroup(fondoLayout.createSequentialGroup()
                .addGap(470, 470, 470)
                .addComponent(jLabel2))
            .addGroup(fondoLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(funcionalidades_text, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(115, 115, 115)
                .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)))
            .addGroup(fondoLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(func2_text, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(func1_text, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(func3_text, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(preguntas_text, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(claro_pregunteme_button, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(fondoLayout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addComponent(jLabel1))
                    .addComponent(personaleyendo, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        fondoLayout.setVerticalGroup(
            fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fondoLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(bienvenido_text, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(descripcion_text, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(fondoLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jLabel5))
                    .addGroup(fondoLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(utepe_text))
                    .addGroup(fondoLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jLabel6)))
                .addComponent(jLabel2)
                .addGap(4, 4, 4)
                .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(fondoLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(funcionalidades_text, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(fondoLayout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(fondoLayout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(fondoLayout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(func2_text, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(fondoLayout.createSequentialGroup()
                                .addGap(61, 61, 61)
                                .addComponent(func1_text, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(func3_text, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(69, 69, 69)
                        .addComponent(preguntas_text, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)
                        .addComponent(claro_pregunteme_button, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(fondoLayout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(personaleyendo, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void claro_pregunteme_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_claro_pregunteme_buttonActionPerformed
        // TODO add your handling code here:
        String Nomb = obtenerDato("Introduce tu nombre:");
        setNombre(Nomb);
        edad = obtenerDato("Introduce tu edad:");
        carrera = obtenerDato("Introduce tu carrera:");
        hobbies = obtenerDato("Introduce tus hobbies:");
    }//GEN-LAST:event_claro_pregunteme_buttonActionPerformed
    private void setNombre(String nomb){
        Nombre = nomb;
    }
    public String getNombre(){
        return Nombre;
    }
    private String getEdad(){
        return edad;
    }
    private String getCarrera(){
        return carrera;
    }
    private String getHobbies(){
        return hobbies;
    }
    public static String obtenerDato(String mensaje) {
        String dato = "";
        boolean datoValido = false;
        while (!datoValido) {
            try {
                dato = JOptionPane.showInputDialog(mensaje);
                if (dato == null || dato.trim().isEmpty()) {
                    throw new IllegalArgumentException("El campo no puede estar vacío");
                }
                datoValido = true;
            } catch (IllegalArgumentException e) {
                JOptionPane.showMessageDialog(null, "Error: " + e.getMessage() + ". Por favor, intenta de nuevo.");
            }
        }
        return dato;
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bienvenido_text;
    private javax.swing.JButton claro_pregunteme_button;
    private javax.swing.JLabel descripcion_text;
    private javax.swing.JPanel fondo;
    private javax.swing.JLabel func1_text;
    private javax.swing.JLabel func2_text;
    private javax.swing.JLabel func3_text;
    private javax.swing.JLabel funcionalidades_text;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel personaleyendo;
    private javax.swing.JLabel preguntas_text;
    private javax.swing.JLabel utepe_text;
    // End of variables declaration//GEN-END:variables

   
}
