/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.libroteca.libroteca;

import com.formdev.flatlaf.FlatLightLaf;
import com.formdev.flatlaf.intellijthemes.materialthemeuilite.FlatMaterialLighterIJTheme;
import com.libroteca.views.Catalogo;
import com.libroteca.views.Inicio;
import com.libroteca.views.Libros;
import com.libroteca.views.Principal;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Desktop;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JPanel;

/**
 *
 * @author Torturado UTP
 */
public class Libroteca extends javax.swing.JFrame {

    /**
     * Creates new form Libroteca
     * @throws java.lang.InterruptedException
     */
    public Libroteca() {
        initComponents();
        initStyles();
        setFecha();
        initContent();
        
    }
    
    private void initContent(){
        ShowJPanel(new Inicio());
    }
    
    public void ShowJPanel(JPanel p){
        p.setSize(838,525);
        p.setLocation(0,0);
    
        contenidos.removeAll();
        contenidos.add(p, BorderLayout.CENTER);
        contenidos.revalidate();
        contenidos.repaint();
    }
    
    private void setFecha(){
        LocalDate now = LocalDate.now();
        Locale spanishLocale = new Locale("es", "ES");
        date_text.setText(now.format(DateTimeFormatter.ofPattern("'Hoy es' EEEE dd 'de' MMM 'de' yyy", spanishLocale)));
    }
    private void initStyles() {
        String texto = "Protégeme, Señor, con tu espíritu... Protégeme, Señor, con tu espíritu... Y déjame sentir el fuego de tu amor Aquí en mi corazón, Señor...";
        title_label.putClientProperty( "FlatLaf.style", "font: bold $h1.regular.font" );
        title_label.setForeground(Color.white);
        nav_text.putClientProperty( "FlatLaf.style", "font: $h3.font" );
        nav_text.setForeground(Color.white);
        date_text.putClientProperty( "FlatLaf.style", "font: $h0.font" );
        date_text.setForeground(Color.white);
        rosario_text.setText(texto);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        sideboard = new javax.swing.JPanel();
        title_label = new javax.swing.JLabel();
        title_separator = new javax.swing.JSeparator();
        principal_button = new javax.swing.JButton();
        catalogo_button = new javax.swing.JButton();
        mis_libros_button = new javax.swing.JButton();
        hover = new javax.swing.JPanel();
        nav_text = new javax.swing.JLabel();
        date_text = new javax.swing.JLabel();
        contenidos = new javax.swing.JPanel();
        rosario_text = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1020, 640));

        background.setBackground(new java.awt.Color(255, 255, 255));

        sideboard.setBackground(new java.awt.Color(102, 0, 153));

        title_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title_label.setText("LibrotecaPTY");
        title_label.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        title_label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                title_labelMouseClicked(evt);
            }
        });

        principal_button.setBackground(new java.awt.Color(102, 0, 153));
        principal_button.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        principal_button.setForeground(new java.awt.Color(255, 255, 255));
        principal_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resourcess/casita.png"))); // NOI18N
        principal_button.setText("Principal");
        principal_button.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 10, 1, 1, new java.awt.Color(0, 0, 0)));
        principal_button.setBorderPainted(false);
        principal_button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        principal_button.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        principal_button.setIconTextGap(10);
        principal_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                principal_buttonActionPerformed(evt);
            }
        });

        catalogo_button.setBackground(new java.awt.Color(102, 0, 153));
        catalogo_button.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        catalogo_button.setForeground(new java.awt.Color(255, 255, 255));
        catalogo_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resourcess/catalog.png"))); // NOI18N
        catalogo_button.setText("Catalogo");
        catalogo_button.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 10, 1, 1, new java.awt.Color(0, 0, 0)));
        catalogo_button.setBorderPainted(false);
        catalogo_button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        catalogo_button.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        catalogo_button.setIconTextGap(10);
        catalogo_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                catalogo_buttonActionPerformed(evt);
            }
        });

        mis_libros_button.setBackground(new java.awt.Color(102, 0, 153));
        mis_libros_button.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        mis_libros_button.setForeground(new java.awt.Color(255, 255, 255));
        mis_libros_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resourcess/libros.png"))); // NOI18N
        mis_libros_button.setText("Mis Libros");
        mis_libros_button.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 10, 1, 1, new java.awt.Color(0, 0, 0)));
        mis_libros_button.setBorderPainted(false);
        mis_libros_button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mis_libros_button.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        mis_libros_button.setIconTextGap(10);
        mis_libros_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mis_libros_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout sideboardLayout = new javax.swing.GroupLayout(sideboard);
        sideboard.setLayout(sideboardLayout);
        sideboardLayout.setHorizontalGroup(
            sideboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(title_label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(sideboardLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(title_separator, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
            .addComponent(principal_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(catalogo_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(mis_libros_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        sideboardLayout.setVerticalGroup(
            sideboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sideboardLayout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(title_label, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(title_separator, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(principal_button, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(catalogo_button, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mis_libros_button, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(293, Short.MAX_VALUE))
        );

        hover.setBackground(new java.awt.Color(0, 102, 0));

        nav_text.setText("Programación de Computadoras/ Proyecto Semestral/ Principal");

        date_text.setText("Hoy es {dayname} {day} de {month} de {year}");

        javax.swing.GroupLayout hoverLayout = new javax.swing.GroupLayout(hover);
        hover.setLayout(hoverLayout);
        hoverLayout.setHorizontalGroup(
            hoverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hoverLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(hoverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(date_text)
                    .addComponent(nav_text))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        hoverLayout.setVerticalGroup(
            hoverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hoverLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(nav_text)
                .addGap(18, 18, 18)
                .addComponent(date_text)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        contenidos.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout contenidosLayout = new javax.swing.GroupLayout(contenidos);
        contenidos.setLayout(contenidosLayout);
        contenidosLayout.setHorizontalGroup(
            contenidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        contenidosLayout.setVerticalGroup(
            contenidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        rosario_text.setText("jLabel1");

        javax.swing.GroupLayout backgroundLayout = new javax.swing.GroupLayout(background);
        background.setLayout(backgroundLayout);
        backgroundLayout.setHorizontalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addGap(190, 190, 190)
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(contenidos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(hover, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGroup(backgroundLayout.createSequentialGroup()
                .addComponent(sideboard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rosario_text, javax.swing.GroupLayout.PREFERRED_SIZE, 606, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 224, Short.MAX_VALUE))
        );
        backgroundLayout.setVerticalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(hover, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(backgroundLayout.createSequentialGroup()
                .addComponent(rosario_text)
                .addGap(99, 99, 99)
                .addComponent(contenidos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(sideboard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void principal_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_principal_buttonActionPerformed
        // TODO add your handling code here:
        Inicio inicio = new Inicio();
        Principal principal = new Principal(inicio);
        principal.initStyles();
        ShowJPanel(new Principal(inicio));
    }//GEN-LAST:event_principal_buttonActionPerformed

    private void catalogo_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_catalogo_buttonActionPerformed
        // TODO add your handling code here:
        ShowJPanel(new Catalogo());
    }//GEN-LAST:event_catalogo_buttonActionPerformed

    private void mis_libros_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mis_libros_buttonActionPerformed
        // TODO add your handling code here:
        ShowJPanel(new Libros());
    }//GEN-LAST:event_mis_libros_buttonActionPerformed

    private void title_labelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_title_labelMouseClicked
        // TODO add your handling code here:
        try {
                    Desktop.getDesktop().browse(new URI("https://github.com/DevSaints/LibreriaPTY"));
                } catch (IOException | URISyntaxException e1) {
                    e1.printStackTrace();
                }
    }//GEN-LAST:event_title_labelMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        FlatMaterialLighterIJTheme.setup();

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Libroteca().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background;
    private javax.swing.JButton catalogo_button;
    private javax.swing.JPanel contenidos;
    private javax.swing.JLabel date_text;
    private javax.swing.JPanel hover;
    private javax.swing.JButton mis_libros_button;
    private javax.swing.JLabel nav_text;
    private javax.swing.JButton principal_button;
    private javax.swing.JLabel rosario_text;
    private javax.swing.JPanel sideboard;
    private javax.swing.JLabel title_label;
    private javax.swing.JSeparator title_separator;
    // End of variables declaration//GEN-END:variables

    
}
